### ISSUE TITLE
nimble version should be updated

### ISSUE THREAD

**Issue by mars2klb** [ire4ever1190/ponairi#12]
This is a great library, but the documentation doesn't match the code that gets installed by nimble because of where the `0.1.0` tag was set.

A new tag should be created and the nimble version updated to match so that nimble installs all the new goodness.

**Comment by ire4ever1190** [comment]
Published a new [release](https://github.com/ire4ever1190/ponairi/releases/tag/0.2.0) :rocket: 

Seems my documentation generator is also a little broke since the [devel](https://tempdocs.netlify.app/ponairi/devel/ponairi.html) docs have also fallen behind :sweat_smile: 

Will close issue once I have finished publishing the new docs.
